import Head from "next/head";
import { SlashIDProvider, useSlashID } from "@slashid/react";
import styles from "../styles/Home.module.css";

const Login = () => {
  const { user, logIn } = useSlashID();
  return (
    <div>
      <h1>/id React SDK</h1>
      <div className="card">
        <button
          onClick={() =>
            logIn({
              handle: {
                // @ts-ignore
                type: process.env.NEXT_PUBLIC_IDENTIFIER_TYPE,
                // @ts-ignore
                value: process.env.NEXT_PUBLIC_IDENTIFIER_VALUE,
              },
              // @ts-ignore
              factor: { method: process.env.NEXT_PUBLIC_AUTH_METHOD },
            })
          }
        >
          Log in
        </button>
        <p>
          <code>{user && user.token}</code>
        </p>
      </div>
      <p className="read-the-docs">
        <a href="https://developer.slashid.dev/">Read the docs</a>
      </p>
    </div>
  );
};

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        <Login />
      </main>
    </div>
  );
}

export default function WrappedHome() {
  const oid = process.env.NEXT_PUBLIC_ORG_ID || "";
  return (
    <SlashIDProvider oid={oid} tokenStorage="localStorage">
      <Home />
    </SlashIDProvider>
  );
}
