import Head from "next/head";
import { useSlashID } from "@slashid/react";
import styles from "../styles/Home.module.css";

const Login = () => {
  const { user, logIn } = useSlashID();
  return (
    <div>
      <div className="card">
        <button
          onClick={() =>
            logIn({
              handle: {
                // @ts-ignore
                type: process.env.NEXT_PUBLIC_IDENTIFIER_TYPE,
                // @ts-ignore
                value: process.env.NEXT_PUBLIC_IDENTIFIER_VALUE,
              },
              // @ts-ignore
              factor: { method: process.env.NEXT_PUBLIC_AUTH_METHOD },
            })
          }
        >
          Log in
        </button>
        <p>
          <code>{user && user.token}</code>
        </p>
      </div>
      <p className="read-the-docs">
        <a href="https://developer.slashid.dev/">Read the docs</a>
      </p>
    </div>
  );
};

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Login powered by <code className={styles.code}>/id</code>
        </p>

        <Login />
      </main>
    </div>
  );
}

export default Home;
