name: Bundle size

on:
  pull_request:
    branches: [main]

jobs:
  bundle-size:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: pnpm build

      # This must be the last task as it will check out the default branch in order to compare the bundle size
      - name: Bundle size check
        run: pnpm danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
