name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: "mcr.microsoft.com/playwright:v1.42.1-jammy"
    strategy:
      matrix:
        node-version: [20.9.0]
        app-name: [react-nextjs, slashid-remix-impl]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check types
        run: pnpm test:types

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Unit tests
        run: pnpm test:unit

      - name: Run E2E tests
        env:
          CI: true
          MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
          MAILOSAUR_SERVER_ID: ${{ secrets.MAILOSAUR_SERVER_ID }}
          APP_NAME: ${{ matrix.app-name }}
        run: pnpm test:e2e --filter tests

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.app-name }}
          path: packages/tests/playwright-report/
          retention-days: 10
