name: E2E
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    container: "mcr.microsoft.com/playwright:v1.42.1-jammy"
    strategy:
      matrix:
        app-name:
          - react-nextjs
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Use Node.js 20.9.0"
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run E2E tests
        env:
          CI: true
          MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
          MAILINATOR_TEAM_DOMAIN: ${{ secrets.MAILINATOR_TEAM_DOMAIN }}
          APP_NAME: ${{ matrix.app-name }}
        run: pnpm test:e2e --filter tests
        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/tests/playwright-report/
          retention-days: 10
